### ISSUE TITLE
CLI error

### ISSUE THREAD

**Issue by TheYahya** [RealAmirali/kutt-cli#2]
I'm getting this error in cli when type `kutt`:
```
Traceback (most recent call last):
  File "/usr/local/bin/kutt", line 6, in <module>
    from kutt.cli import cli
ImportError: No module named kutt.cli
```

**Comment by univa64** [comment]
I'm sorry about this looooooong time waiting  
plz make sure you used python3 (python3-pip) to install and run the `kutt`  
This error maybe is for python2
