### ISSUE TITLE
kutt config-api does not seem to exist

### ISSUE THREAD

**Issue by ucphinni** [RealAmirali/kutt-cli#5]
Using windows 10 64 bit python 3.7 from python.org

Created api-key on http://kutt.it website.
Tried to run "kutt config-api" from command line to configure the key

program does not recognize it as a valid command

**Comment by sjbat** [comment]
Try:

kutt config_api

With _ underscore instead of -

**Comment by RealAmirali** [comment]
It should be work. I'm on python3.8 on windows and `config-api` is working.

But you can configure manually. Put your API KEY in this file:

`C:\Users\{USERNAME}\AppData\Roaming\kutt-cli\apikey.txt`

**Comment by RealAmirali** [comment]
> 
> 
> Using windows 10 64 bit python 3.7 from python.org
> 
> Created api-key on http://kutt.it website.
> Tried to run "kutt config-api" from command line to configure the key
> 
> program does not recognize it as a valid command

It should be work. I'm on python3.8 on windows and `config-api` is working.
But you can configure manually. Put your API KEY in this file:
`C:\Users\{USERNAME}\AppData\Roaming\kutt-cli\apikey.txt`
