### ISSUE TITLE
Reuse must be boolean.

### ISSUE THREAD

**Issue by amirarj** [RealAmirali/kutt-cli#6]
got this error when using reuse option

`{'code': 400, 'data': {'error': 'Reuse must be boolean.'}}`

code:
`obj = kutt.submit(API, 'https://github.com/', reuse=True)`
`print(obj)`

**Comment by RealAmirali** [comment]
Thanks for report this.
It fixed in d5a16b43dec0163c6d7aff531f09bcbe917673f8 at version [1.2.4.1](https://pypi.org/project/kutt/1.2.4.1/) on pypi
